### ISSUE TITLE
Error:"::tcl::tm::UnknownHandler ::tclPkgUnknown math::statistics

### ISSUE THREAD

**Issue by Hosnieht** [amaelkady/OpenSEES_Models_SMF#1]
Hello
Thank you for giving smf models
I have a problem,when i run models in my editor( notepad++) show this error. I searched it and do anything to solve it but I couldn't succeed. 
My activetcl: 8.6.11
Opensees.exe 3.3.0

**Comment by amaelkady** [comment]
It seems that you are missing the math package from your tkl installation. You can try downloading the "lib" folder uploaded on my GitHub FM-2D repo and then place it on your pc (one level above the folder where the opensees.exe exist).

I would also recommend you try using the software FM-2D to generate and run similar models. FM-2D is very easy to use and employs the state-of-the-art numerical models which are continuously being updated.

**Comment by Hosnieht** [comment]
thank you for your attention & recommendation
I have a question, I am reading essay & manual of FM-2D software, what is the limitation of this software? I'm working in Column base connections & i should model details of column base.
